<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{bd2073ad-7f80-4a92-a7bb-c30c81baa107}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nContador AT %Q*: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nContador := nContador + 2;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="12" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>